package com.destroflyer.jme3.effekseer.test;

import com.destroflyer.jme3.effekseer.virtual.model.ParticleEffect;
import com.destroflyer.jme3.effekseer.virtual.reader.EffekseerReader;
import com.jme3.math.FastMath;

import java.io.File;
import java.util.ArrayList;
import java.util.Map;
import java.util.TreeMap;

public class TestParticleEffects {

    public TestParticleEffects() {
        initializeInfo();
    }
    public static final String ASSET_ROOT = "./";
    private EffekseerReader effekseerReader = new EffekseerReader();
    private final TreeMap<String, TestParticleEffectInfo> testParticleEffectInfoMap = new TreeMap<>();

    private void initializeInfo() {
        // AndrewFM01
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_halo", null);
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_halo2", null);
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_radial", null);
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_radial2", null);
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_shockwave", null);
        testParticleEffectInfoMap.put("AndrewFM01\\actionLines_strip", null);
        testParticleEffectInfoMap.put("AndrewFM01\\blue_laser", TestParticleEffectInfo.builder().quality(1).cameraSpeed(0.1f).build());
        testParticleEffectInfoMap.put("AndrewFM01\\boss_death", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).cameraHeight(0).build());
        testParticleEffectInfoMap.put("AndrewFM01\\drill", TestParticleEffectInfo.builder().quality(1).cameraSpeed(0.1f).build());
        testParticleEffectInfoMap.put("AndrewFM01\\electric_dust", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).build());
        testParticleEffectInfoMap.put("AndrewFM01\\fire", null);
        testParticleEffectInfoMap.put("AndrewFM01\\hit_eff", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("AndrewFM01\\magic_circle", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("AndrewFM01\\smallTexturesRibbon", null);
        testParticleEffectInfoMap.put("AndrewFM01\\smallTexturesSquareWave_orbital", null);
        // Effekseer01
        testParticleEffectInfoMap.put("Effekseer01\\Homing_Laser01", TestParticleEffectInfo.builder().cameraDistance(20).build());
        testParticleEffectInfoMap.put("Effekseer01\\Laser01", TestParticleEffectInfo.builder().quality(1).cameraAngle(1.75f * FastMath.PI).cameraDistance(50).build());
        testParticleEffectInfoMap.put("Effekseer01\\Laser02", TestParticleEffectInfo.builder().quality(1).cameraAngle(1.75f * FastMath.PI).cameraDistance(50).build());
        testParticleEffectInfoMap.put("Effekseer01\\Laser03", TestParticleEffectInfo.builder().quality(2).cameraAngle(0.25f * FastMath.PI).cameraDistance(60).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Distortion", TestParticleEffectInfo.builder().quality(1).cameraHeight(10).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_GeneratingPosition1", null);
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Model_UV", null);
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Ribbon_Parent", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Ribbon_Sword", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Ring_Shape1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Ring_Shape2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Sprite_BillBoard", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Sprite_Fixed", TestParticleEffectInfo.builder().quality(1).cameraAngle(0.25f * FastMath.PI).cameraHeight(0).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Sprite_FixedYAxis", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Effekseer01\\Simple_Track1", TestParticleEffectInfo.builder().quality(1).cameraDistance(50).cameraHeight(70).build());
        // MAGICALxSPIRAL
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Gohlem1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Salamander1", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Salamander2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Salamander4", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Sylph1", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Sylph2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Undine1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\A_Undine2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\AquaPoint", TestParticleEffectInfo.builder().quality(2).cameraDistance(2).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Attack_Impact", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Attack1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Attack2", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Attack5", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Attack6", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Breakdown", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\FirePot1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\FirePot2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke2", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke3", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke4", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke5", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke6", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke7", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\foot_smoke8", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem_Shield1", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem_Shield2", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem5", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem7", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Gohlem11", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Holy1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Holy2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Icicle1", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Icicle2", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Icicle3", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\IcicleBroken", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\IcicleLocus", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Lance3", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Lance4", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Lance5", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic1_earth", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic1_fire", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic1_holy", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic1_water", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic1_wind", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic2_earth", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic2_fire", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic2_holy", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic2_water", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Magic2_wind", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\MagicArea", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\meteo1", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Rock1", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Rock2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander3", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander4", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander5", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander6", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander7", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander11", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander12", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\salamander13", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander14", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Salamander15", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Snowman1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\StairBroken", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\StairBroken3", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph3", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph4", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph5", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph6", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph7", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph8", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph10", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph11", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph13", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Sylph15", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Thunder1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Thunder2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Thunder3", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Topwater1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine3", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine4", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine5", TestParticleEffectInfo.builder().quality(2).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine6", TestParticleEffectInfo.builder().quality(1).cameraDistance(5).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine8", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine11", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Undine13", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Water_Impact", null);
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\WHead1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\WHead2", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\WHead3", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        testParticleEffectInfoMap.put("MAGICALxSPIRAL\\Wind_Impact", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).build());
        // NextSoft01
        testParticleEffectInfoMap.put("NextSoft01\\HealPotion1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\HealPotion2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicCold", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicDark", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicFire1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicFire2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicHeal1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicHeal2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicLight", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicMeteo", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicShield", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicSword", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicThunder", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicTornade", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NextSoft01\\MagicWater", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NextSoft01\\PowerUp", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\Spear1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\Spear2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\Sword1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NextSoft01\\Sword2", TestParticleEffectInfo.builder().quality(1).build());
        // NitoriBox
        testParticleEffectInfoMap.put("NitoriBox\\AddEnemy", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\Aya_Attack", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\BlazingStar", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\Boss_Death", TestParticleEffectInfo.builder().quality(12).build());
        testParticleEffectInfoMap.put("NitoriBox\\BreakUnit", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\Charge", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\CorrectItem1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\CorrectItem2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\CorrectItem3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\Explosion", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\Flan_Fire", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\GetKey", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\GetKeyItem1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\GetKeyItem2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\GetLife", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("NitoriBox\\Marisa_Damage", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\Marisa_Laser", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\Marisa_MasterSpark", TestParticleEffectInfo.builder().quality(1).frameLength(1f / 120).cameraDistance(30).cameraHeight(20).cameraSpeed(0.2f).build());
        testParticleEffectInfoMap.put("NitoriBox\\Marisa_Shot", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\OpenKey", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("NitoriBox\\Tenshi_Sword", TestParticleEffectInfo.builder().quality(1).cameraDistance(30).cameraHeight(20).build());
        // Pierre01
        testParticleEffectInfoMap.put("Pierre01\\Atmosphere", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre01\\Background", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 240).cameraAngle(FastMath.PI).cameraDistance(60).cameraHeight(0).build());
        testParticleEffectInfoMap.put("Pierre01\\Flame", TestParticleEffectInfo.builder().frameLength(1f / 144).quality(2).build());
        testParticleEffectInfoMap.put("Pierre01\\Herald", TestParticleEffectInfo.builder().quality(2).cameraAngle(0.15f * FastMath.PI).build());
        testParticleEffectInfoMap.put("Pierre01\\HolySandstorm", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 96).cameraAngle(0.25f * FastMath.PI).cameraDistance(50).cameraHeight(40).cameraSpeed(0.2f).build());
        testParticleEffectInfoMap.put("Pierre01\\LightningStrike", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 96).cameraDistance(120).cameraHeight(100).build());
        testParticleEffectInfoMap.put("Pierre01\\MissileBoost", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 120).cameraHeight(30).build());
        testParticleEffectInfoMap.put("Pierre01\\MonsterRoar", null);
        testParticleEffectInfoMap.put("Pierre01\\PhantasmMeteor", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 96).cameraDistance(40).build());
        testParticleEffectInfoMap.put("Pierre01\\PhantasmMeteor_Single", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 96).cameraDistance(40).build());
        testParticleEffectInfoMap.put("Pierre01\\SonicBoom", TestParticleEffectInfo.builder().quality(1).frameLength(1f / 96).cameraAngle(-0.5f * FastMath.PI).cameraDistance(50).cameraHeight(30).cameraSpeed(0.2f).build());
        // Pierre02
        testParticleEffectInfoMap.put("Pierre02\\Benediction", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\BloodLance", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\CosmicMist", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\FeatherBomb", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\FireBall", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\GateOfCalve", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 72).cameraAngle(0.25f * FastMath.PI).cameraDistance(30).cameraHeight(20).build());
        testParticleEffectInfoMap.put("Pierre02\\LossOfBlood", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("Pierre02\\Sword_Ember", null);
        testParticleEffectInfoMap.put("Pierre02\\Sword_Lightning", null);
        testParticleEffectInfoMap.put("Pierre02\\Sword_Moonlight", null);
        testParticleEffectInfoMap.put("Pierre02\\Sword_Sacredlight", null);
        testParticleEffectInfoMap.put("Pierre02\\Sword_Storm", null);
        // ProjectDanmakuGirls
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\bom", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\mc01", null);
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\mc02", null);
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\sogeki", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\warningArea", null);
        testParticleEffectInfoMap.put("ProjectDanmakuGirls\\wind", TestParticleEffectInfo.builder().quality(2).cameraAngle(0.15f * FastMath.PI).build());
        // Suzuki01
        testParticleEffectInfoMap.put("Suzuki01\\001_magma_effect\\aura", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 96).cameraDistance(3).build());
        testParticleEffectInfoMap.put("Suzuki01\\002_sword_effect\\sword", null);
        testParticleEffectInfoMap.put("Suzuki01\\003_snowstorm_effect\\snowstorm11", null);
        // TouhouStrategy
        testParticleEffectInfoMap.put("TouhouStrategy\\aya_senpu_area", TestParticleEffectInfo.builder().frameLength(1f / 36).quality(2).cameraDistance(30).cameraHeight(20).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\marisa_master_area", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 24).cameraAngle(-0.05f * FastMath.PI).cameraDistance(30).cameraHeight(20).cameraSpeed(0.1f).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\miko_hihou_effect", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\patch_stElmo_area", TestParticleEffectInfo.builder().quality(2).cameraHeight(20).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\patch_stElmo_area_2", TestParticleEffectInfo.builder().quality(2).cameraHeight(20).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\remilia_heart_bullet", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 24).cameraAngle(0.15f * FastMath.PI).cameraDistance(30).cameraSpeed(-0.1f).build());
        testParticleEffectInfoMap.put("TouhouStrategy\\utsuho_sun_area", TestParticleEffectInfo.builder().quality(2).frameLength(1f / 36).build());
        // tktk01
        testParticleEffectInfoMap.put("tktk01\\Arrow1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\Arrow2", TestParticleEffectInfo.builder().quality(2).cameraDistance(5).cameraHeight(20).build());
        testParticleEffectInfoMap.put("tktk01\\Blow1", TestParticleEffectInfo.builder().quality(1).cameraDistance(10).cameraHeight(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Blow4", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Blow5", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow6", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow7", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow8", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Blow9", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow10", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow11", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Blow12", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow13", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Blow14", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Blow15", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Cure1", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Cure2", TestParticleEffectInfo.builder().quality(2).cameraDistance(30).build());
        testParticleEffectInfoMap.put("tktk01\\Cure3", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Cure4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Cure5", TestParticleEffectInfo.builder().quality(1).cameraDistance(50).build());
        testParticleEffectInfoMap.put("tktk01\\Cure6", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Cure7", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Dark1", TestParticleEffectInfo.builder().quality(2).cameraDistance(30).build());
        testParticleEffectInfoMap.put("tktk01\\Dark2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Dark3", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire1", TestParticleEffectInfo.builder().quality(2).cameraHeight(2).build());
        testParticleEffectInfoMap.put("tktk01\\Fire2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire3", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire5", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire6", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Fire7", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Fire8", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\hozyo1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\hozyo2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\hozyo3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\hozyo4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\hozyo5", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Light1", TestParticleEffectInfo.builder().quality(2).cameraDistance(30).build());
        testParticleEffectInfoMap.put("tktk01\\Light2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Light3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Light4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Magic1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Magic2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Soil1", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Sword1", TestParticleEffectInfo.builder().quality(2).cameraDistance(40).build());
        testParticleEffectInfoMap.put("tktk01\\Sword2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\Sword3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword4", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword5", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword6", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword7", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword8", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword9", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword10", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword11", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\Sword12", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword13", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword14", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword15", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword16", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk01\\Sword17", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Sword18", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\Sword19", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk01\\Sword20", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Sword21", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Sword22", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk01\\Wind1", TestParticleEffectInfo.builder().quality(2).cameraDistance(30).build());
        testParticleEffectInfoMap.put("tktk01\\Wind2", TestParticleEffectInfo.builder().quality(1).build());
        // tktk02
        testParticleEffectInfoMap.put("tktk02\\Blow1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Blow2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Blow3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Blow4", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Blow5", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Blow6", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Claw1", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Claw2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Claw3", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Claw4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Dark1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Dark2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Fire1", null);
        testParticleEffectInfoMap.put("tktk02\\Fire2", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Fire3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Fire4", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Fire5", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Fire6", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Fire7", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Fire8", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Gun1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Gun2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Gun3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Gun4", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Gun5", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Gun6", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Gun7", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Gun8", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Gun9", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Light1", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Light2", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Light3", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Light4", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Spear1", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Spear2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Spear3", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Spear4", TestParticleEffectInfo.builder().quality(2).build());
        testParticleEffectInfoMap.put("tktk02\\Sword1", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Sword2", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Sword3", TestParticleEffectInfo.builder().quality(0).build());
        testParticleEffectInfoMap.put("tktk02\\Sword4", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Sword5", TestParticleEffectInfo.builder().quality(1).build());
        testParticleEffectInfoMap.put("tktk02\\Sword6", TestParticleEffectInfo.builder().quality(2).build());
    }

    ArrayList<TestParticleEffect> getTestParticleEffects(Integer quality) {
        ArrayList<TestParticleEffect> testParticleEffects = new ArrayList<>();
        for (Map.Entry<String, TestParticleEffectInfo> entry : testParticleEffectInfoMap.entrySet()) {
            TestParticleEffectInfo info = entry.getValue();
            if ((info != null) && ((quality == null) || (info.getQuality() == quality))) {
                File file = new File("./samples/" + entry.getKey() + ".efkproj");
                ParticleEffect particleEffect = effekseerReader.read(ASSET_ROOT, file);
                TestParticleEffect testParticleEffect = TestParticleEffect.builder()
                        .directory(file.getParent())
                        .fileName(file.getName())
                        .particleEffect(particleEffect)
                        .info(info)
                        .build();
                testParticleEffects.add(testParticleEffect);
            }
        }
        return testParticleEffects;
    }
}
